training:
  epochs: 500
  batch_size: 16
  validation_split: 0.2
  optimizer: adam

threshold:
  method: "sigma"
  sigma: 3
  percentile: 75

cnn2d:
  filters: [32, 16]

cnn1d:
  filters: [128, 64]

lstm:
  latent_dim: 128

output:
  folder: "outputs/semisupervised"

dataset:
  raw_folder: "C:/Users/jpedr/Desktop/TRACTICIAN_Challenge/part_2/data"
  output_folder: "prepared_data"
  nperseg: 256
  noverlap: 224
  use_db_scale: true
  metadata_file: "C:/Users/jpedr/Desktop/TRACTICIAN_Challenge/part_2/part_3_metadata.csv"
  extra_features:
    rms: true
    spectral_centroid: true

